name: razorpay_flutter
description: Flutter plugin for Razorpay SDK. To know more about Razorpay, visit http://razorpay.com.
version: 1.3.6
homepage: https://github.com/razorpay/razorpay-flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  eventify:
  package_info_plus: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
  plugin:
    platforms:
      android:
        package: com.razorpay.razorpay_flutter
        pluginClass: RazorpayFlutterPlugin
      ios:
        pluginClass: RazorpayFlutterPlugin
