// ignore_for_file: constant_identifier_names

enum RazorpayCurrency {
  AED("United Arab Emirates Dirham"),
  ALL("Albanian lek"),
  AMD("Armenian dram"),
  ARS("Argentine peso"),
  AUD("Australian dollar"),
  AWG("Aruban florin"),
  BBD("Barbadian dollar"),
  BDT("Bangladeshi taka"),
  BMD("Bermudian dollar"),
  BND("Brunei dollar"),
  BOB("Bolivian boliviano"),
  BSD("Bahamian dollar"),
  BWP("Botswana pula"),
  BZD("Belize dollar"),
  CAD("Canadian dollar"),
  CHF("Swiss franc"),
  CNY("Chinese yuan renminbi"),
  COP("Colombian peso"),
  CRC("Costa Rican colon"),
  CUP("Cuban peso"),
  CZK("Czech koruna"),
  DKK("Danish krone"),
  DOP("Dominican peso"),
  DZD("Algerian dinar"),
  EGP("Egyptian pound"),
  ETB("Ethiopian birr"),
  EUR("European euro"),
  FJD("Fijian dollar"),
  GBP("Pound sterling"),
  GHS("Ghanian Cedi"),
  GIP("Gibraltar pound"),
  GMD("Gambian dalasi"),
  GTQ("Guatemalan quetzal"),
  GYD("Guyanese dollar"),
  HKD("Hong Kong dollar"),
  HNL("Honduran lempira"),
  HRK("Croatian kuna"),
  HTG("Haitian gourde"),
  HUF("Hungarian forint"),
  IDR("Indonesian rupiah"),
  ILS("Israeli new shekel"),
  INR("Indian rupee"),
  JMD("Jamaican dollar"),
  KES("Kenyan shilling"),
  KGS("Kyrgyzstani som"),
  KHR("Cambodian riel"),
  KYD("Cayman Islands dollar"),
  KZT("Kazakhstani tenge"),
  LAK("Lao kip"),
  LBP("Lebanese pound"),
  LKR("Sri Lankan rupee"),
  LRD("Liberian dollar"),
  LSL("Lesotho loti"),
  MAD("Moroccan dirham"),
  MDL("Moldovan leu"),
  MKD("Macedonian denar"),
  MMK("Myanmar kyat"),
  MNT("Mongolian tugrik"),
  MOP("Macanese pataca"),
  MUR("Mauritian rupee"),
  MVR("Maldivian rufiyaa"),
  MWK("Malawian kwacha"),
  MXN("Mexican peso"),
  MYR("Malaysian ringgit"),
  NAD("Namibian dollar"),
  NGN("Nigerian naira"),
  NIO("Nicaraguan cordoba"),
  NOK("Norwegian krone"),
  NPR("Nepalese rupee"),
  NZD("New Zealand dollar"),
  PEN("Peruvian sol"),
  PGK("Papua New Guinean kina"),
  PHP("Philippine peso"),
  PKR("Pakistani rupee"),
  QAR("Qatari riyal"),
  RUB("Russian ruble"),
  SAR("Saudi Arabian riyal"),
  SCR("Seychellois rupee"),
  SEK("Swedish krona"),
  SGD("Singapore dollar"),
  SLL("Sierra Leonean leone"),
  SOS("Somali shilling"),
  SSP("South Sudanese pound"),
  SVC("Salvadoran colón"),
  SZL("Swazi lilangeni"),
  THB("Thai baht"),
  TTD("Trinidad and Tobago dollar"),
  TZS("Tanzanian shilling"),
  USD("United States dollar"),
  UYU("Uruguayan peso"),
  UZS("Uzbekistani so'm"),
  YER("Yemeni rial"),
  ZAR("South African rand");
  final String currencyName;
  const RazorpayCurrency(this.currencyName);
}
